made a simple pause menu
chwerth/RAstral_Rampart pull request #40
Opened 2020-05-11 22:59 UTC by Rw552

Included the functionality to quit if the player wants, as well as resume from where they paused. also hides the screen so the player can't abuse the menu to think about the game itself

2020-05-11 22:59 UTC, pep8speaks commented
Hello @Rw552! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`spinny_gun.py`](https://github.com/chwerth/SpinnyGun/blob/4643f468a0c584b50e4d9c13564e92020f9a6efd/spinny_gun.py):

> [Line 78:1](https://github.com/chwerth/SpinnyGun/blob/4643f468a0c584b50e4d9c13564e92020f9a6efd/spinny_gun.py#L78): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 83:1](https://github.com/chwerth/SpinnyGun/blob/4643f468a0c584b50e4d9c13564e92020f9a6efd/spinny_gun.py#L83): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 84:1](https://github.com/chwerth/SpinnyGun/blob/4643f468a0c584b50e4d9c13564e92020f9a6efd/spinny_gun.py#L84): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2020-05-11 23:11 UTC, chwerth commented
Getting #39 every time I try to run this branch. Is that just me?

2020-05-11 23:14 UTC, Rw552 commented
> Getting #39 every time I try to run this branch. Is that just me?

@chwerth I'm not having any problems with #39 at all.

2020-05-11 23:16 UTC, chwerth commented
![pause](https://user-images.githubusercontent.com/48846148/81621194-6c158480-93b3-11ea-9eba-70840b1a523e.gif)

Ouch. I'm still getting it. I'll try restarting my computer and re-cloning the whole thing just to be sure.

2020-05-12 00:02 UTC, chwerth requested changes
Looks good. Just got a few comments. Also, it looks like this did fix the crashing, as long as you use python 3.7.5+. Not sure why. Oh well. Worth noting for packaging later.

2020-05-12 00:02 UTC, chwerth commented on spinny_gun.py
> +                    quit()
```suggestion
                    exit_game()
```

Should probably use the same exit game function throughout, in case we want to attach anything to it later.

2020-05-12 00:02 UTC, chwerth commented on spinny_gun.py
> +    global pause
As long as pause is a global, can we make it all caps?

2020-05-12 00:02 UTC, chwerth commented on spinny_gun.py
> +                quit()
```suggestion
                exit_game()
```

2020-05-12 00:02 UTC, chwerth commented on spinny_gun.py
> +                if event.key == pygame.K_p:
Can we make the pause button be "Esc"? People will probably expect that to be the pause button.

It would also be the unpause button, in that case.

2020-05-12 00:02 UTC, chwerth commented on spinny_gun.py
> +    pygame.mixer.music.set_volume(0.25)
```suggestion
    pygame.mixer.music.set_volume(0.5)
```

Was this too loud on yours? It was ok on mine. I feel like 0.25 is a little low

2020-05-12 00:34 UTC, chwerth approved these changes

2020-05-12 00:35 UTC, merged