developed Hud object
chwerth/RAstral_Rampart pull request #77
Opened 2020-05-22 22:55 UTC by Rw552

resolves #46 #64 #58

2020-05-22 22:55 UTC, pep8speaks commented
Hello @Rw552! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`game_loop.py`](https://github.com/chwerth/RAstral_Rampart/blob/b094dbccd425c2e2600a59373bd29ca0268449f7/game_loop.py):

> [Line 60:80](https://github.com/chwerth/RAstral_Rampart/blob/b094dbccd425c2e2600a59373bd29ca0268449f7/game_loop.py#L60): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (110 > 79 characters)
> [Line 73:24](https://github.com/chwerth/RAstral_Rampart/blob/b094dbccd425c2e2600a59373bd29ca0268449f7/game_loop.py#L73): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 127:1](https://github.com/chwerth/RAstral_Rampart/blob/b094dbccd425c2e2600a59373bd29ca0268449f7/game_loop.py#L127): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2020-05-22 23:39 UTC, chwerth requested changes
On my phone right now, but looks good so far. Can we also remove the __pycache__ folder?

2020-05-22 23:39 UTC, chwerth commented on game_loop.py
> +class Hud(object):
Now that it's done, can we move this to its own file?

2020-05-22 23:39 UTC, chwerth commented on game_loop.py
> +        score = hud.draw_score(player.score)
Can we fit all this in one method? The one method (like maybe "draw") could just call all the other ones within the class

2020-05-22 23:41 UTC, Rw552 commented
> 
> 
> On my phone right now, but looks good so far. Can we also remove the **pycache** folder?

I have no idea what that folder is for tbh.

2020-05-22 23:42 UTC, Rw552 commented on game_loop.py
> +class Hud(object):
yeah I'll work on that next

2020-05-22 23:42 UTC, Rw552 commented on game_loop.py
> +        score = hud.draw_score(player.score)
sure thing

2020-05-23 00:04 UTC, chwerth requested changes
Okay now i'm actually at a computer. This is great so far. Good work

2020-05-23 00:04 UTC, chwerth commented on game_loop.py
> +        score = hud.draw_score(player.score)
Wait, what's returned into `score`? What is this line for?

2020-05-23 00:04 UTC, chwerth commented on hud.py
> +            "Press 'SPACE' to Fire!",
- [ ] Can we move this to the bottom left? I tested this out and the top of the screen feels weird to me
- [ ] Can we add `esc` to pause?
- [ ] Did you find any free spacebar/esc icons? I was thinking something like, bottom left corner, `pause {esc icon} fire {spacebar icon}` if possible

2020-05-23 00:05 UTC, Rw552 commented on game_loop.py
> +        score = hud.draw_score(player.score)
oh that's old, I can delete that.

2020-05-23 00:07 UTC, chwerth commented on hud.py
> +            "Press 'SPACE' to Fire!",
It would also be fine to do icons in a separate, later PR to make this simpler for now

2020-05-23 00:22 UTC, Rw552 commented on hud.py
> +            "Press 'SPACE' to Fire!",
> Did you find any free spacebar/esc icons? I was thinking something like, bottom left corner, {esc icon} pause {spacebar icon} fire if possible

I couldn't find a good spacebar icon, so i opted to not use an icon for either

2020-05-23 00:26 UTC, chwerth commented on hud.py
> +            "Press 'SPACE' to Fire!",
Aight. If we find one in the future, can just swap it in.

2020-05-23 00:34 UTC, chwerth approved these changes

2020-05-23 00:34 UTC, chwerth commented
Looks good to me

2020-05-23 00:34 UTC, merged